---
parameters:
    user:
        # The directory (in user root folder) containing the assets Swag will use
        # if null, the data & pages must be located at the root of the user folder
        assets: swag

        # The directory Swag will use to build the data variable
        data: data

        # The directory Swag will browse to process pages
        pages: pages

        # The destination directory where to put processed pages
        destination: static_website

    generator:
        twig:
            cache: false
            autoescape: false

services:
    swag.resources_conformer:
        class: Swag\Service\ResourcesConformer
        arguments: ['%user%']

    swag.file_system:
        class: Swag\Model\FileSystem\FileSystem
        arguments: ['%pages_directory%', '%destination_directory%']

    swag.template_loader:
        class: \Twig_Loader_Filesystem
        arguments: ['%pages_directory%']

    swag.template:
        class: \Twig_Environment
        arguments: ['@swag.template_loader', "@=parameter('generator')['twig']"]

    swag.notifier:
        class: Swag\Service\notifier
        arguments: ['%console_output%']

    # Pages generation
    swag.page_engine:
        class: Swag\Model\Page\Engine
        arguments: ['%pages_directory%']
        calls:
            - [addPageHandler, ['@swag.page_handler.iterative_twig']]
            - [addPageHandler, ['@swag.page_handler.twig']]
            - [addPageHandler, ['@swag.page_handler.skip']]
            - [addPageHandler, ['@swag.page_handler.asset']]

    swag.page_handler.iterative_twig:
        class: Swag\Model\Page\Handler\IterativeTwigHandler
        arguments: ['@swag.template', '@swag.file_system']

    swag.page_handler.twig:
        class: Swag\Model\Page\Handler\TwigHandler
        arguments: ['@swag.template', '@swag.file_system']

    swag.page_handler.skip:
        class: Swag\Model\Page\Handler\SkipHandler
        arguments: ['@swag.file_system']

    swag.page_handler.asset:
        class: Swag\Model\Page\Handler\AssetHandler
        arguments: ['@swag.file_system']

    # data building
    swag.data_builder:
        class: Swag\Model\Data\DataBuilder
        arguments: ['%data_directory%', '@swag.notifier']
        calls:
            - [addDataHandler, ['@swag.data_handler.directory']]
            - [addDataHandler, ['@swag.data_handler.yaml']]
            - [addDataHandler, ['@swag.data_handler.markdown']]

    swag.data_handler.directory:
        class: Swag\Model\Data\Handler\DirectoryHandler

    swag.data_handler.yaml:
        class: Swag\Model\Data\Handler\YamlHandler

    swag.data_handler.markdown:
        class: Swag\Model\Data\Handler\MarkdownHandler


