---
parameters:
    user:
        # The directory (in user root folder) containing the assets Swag will use
        # if null, the data & pages must be located at the root of the user folder
        assets: swag

        # The directory Swag will use to build the data variable
        data: data

        # The directory Swag will browse to process pages
        pages: pages

        # The destination directory where to put processed pages
        destination: static_website

    generator:
        twig:
            cache: false
            autoescape: false

services:
    swag.resources_conformer:
        class: Swag\Service\ResourcesConformer
        arguments: ['%user%']

    swag.file_system:
        class: Swag\Model\FileSystem\FileSystem
        arguments: ['%pages_directory%', '%destination_directory%']

    swag.template_loader:
        class: \Twig_Loader_Filesystem
        arguments: ['%pages_directory%']

    swag.template:
        class: \Twig_Environment
        arguments: ['@swag.template_loader', "@=parameter('generator')['twig']"]

    swag.page_engine:
        class: Swag\Model\Page\Engine
        arguments: ['%pages_directory%']
        calls:
            - [addPageHandler, ['@swag.iterative_twig_handler']]
            - [addPageHandler, ['@swag.twig_handler']]
            - [addPageHandler, ['@swag.skip_handler']]
            - [addPageHandler, ['@swag.asset_handler']]

    swag.iterative_twig_handler:
        class: Swag\Model\Page\Handler\IterativeTwigHandler
        arguments: ['@swag.template', '@swag.file_system']

    swag.twig_handler:
        class: Swag\Model\Page\Handler\TwigHandler
        arguments: ['@swag.template', '@swag.file_system']

    swag.skip_handler:
        class: Swag\Model\Page\Handler\SkipHandler
        arguments: ['@swag.file_system']

    swag.asset_handler:
        class: Swag\Model\Page\Handler\AssetHandler
        arguments: ['@swag.file_system']

