#!/usr/bin/php
<?php

/*
 * @Author: Woecifaun
 * @License: view License file if any
 */

require_once __DIR__.'/autoload.php';

$app = new Silly\Application();

$app
->command('generate [--source=]', ['Swag\\Generator', 'main'])
->descriptions('Generate your Static Website with SWaG!', [
    '--source' => 'Absolute path to your source directory.',
]);

$app->run();
